### ISSUE TITLE
Document how to store Liman's state in a volume

### ISSUE THREAD

**Issue by lukaspj** [salihciftci/liman#14]
**Detailed Description**

It doesn't mention how to persist the Liman container's state in the README.
Adding a few lines about which folders to mount, helps maintaining the Liman container between recreation of containers (new version, accidental tear-down, network change).

**Context**

Arguably, the state Liman currently saves is very small (just a hash of the root password), and the cases where it is desirable to save the state are few and unlikely to occur.
However, in case someone needed this information or if more state is added to the future, it wouldn't hurt to be proactive about documenting this detail.

**Comment by salihciftci** [comment]
> Liman currently saves is very small

Yes, Liman only hashing root password and save that. While there is no big storage I didn't write any explanation to `README.md`. After SQLite improvement Liman will store sessions, user, user permissions etc. I was thinking about to write a explanation after improvement. Maybe that was a mistake.

I'm closing this issue while you already had a pull request. But feel free to comment.
