### ISSUE TITLE
Display containers grouped by stacks

### ISSUE THREAD

**Issue by lukaspj** [salihciftci/liman#17]
**Detailed Description**

Portainer has a "stack" view, which lets you inspect all containers based on their stack. This can be either a Docker stack or a docker-compose stack.
It would be nice to have this same functionality in Liman, alternatively being able to see all containers for a network would fulfill a similar purpose.

**Context**

Having a list of containers running on the server is all well and good until you have a lot of them. At my work, we have 10 docker-compose stacks, each hosting ~10 containers. That's a lot of unstructured information if we just get it as a list of containers.
Each of these stacks represent a separate environment, therefore being able to inspect each of these stacks (environments in our case) separately, would greatly improve the ease-of-use of Liman.

This is only really an issue when running a very big number of containers, as Liman currently works very well with 10 or even 20 containers on a single server.

**Comment by lukaspj** [comment]
I don't know how Portainer gets the compose-stacks, I have not been able to figure out how they do that.
But if a network-grouping could fulfill the same purpose, a `docker network ls` followed by a `docker inspect <networkd id>` for each network, can find containers belonging to each network.

Worth noting is that doing it based on networks means containers can exist in multiple networks, and 2 containers from the same compose-stack don't necessarily show up in the same networks.

**Comment by salihciftci** [comment]
With #19 I will look at what can I do. 

> That's a lot of unstructured information if we just get it as a list of containers.

That's important. We need to keep clean and simple every page. I will look what can do about it.
