### ISSUE TITLE
Does the roadmap include an API ?

### ISSUE THREAD

**Issue by bpetit** [salihciftci/liman#2]
Having a web interface is great. Having a REST API would be very interessting to, is this in the roadmap ?

Thanks

**Comment by salihciftci** [comment]
API feature added with [v0.3](https://github.com/salihciftci/liman/releases/tag/v0.3)

Here is the basic usage:
```
curl -i http://localhost:8080/api/status?key=XXX
```

For more information check out [wiki](https://github.com/salihciftci/liman/wiki/API-Usage).
