### ISSUE TITLE
after login page loads forever 

### ISSUE THREAD

**Issue by vbrinza** [salihciftci/liman#3]
I run the container with 
`docker run -dit --name liman -e pass=test12345 -p 8082:8080 -v /var/run/docker.sock:/var/run/docker.sock salihciftci/liman`

CentOS Linux release 7.4.1708 (Core)
Docker version 17.12.0-ce, build c97c6d6

After writing the password the page loads forever and nothing happens.

**Comment by salihciftci** [comment]
Hey @vbrinza 

Can you send me the logs?

**Comment by vbrinza** [comment]
I see nothing more than

`docker logs 7315bc141e46
2018/04/25 11:31:04 Listening :8080..`

it probably needs more verbosity

**Comment by salihciftci** [comment]
I run the same command as you did and everythings works fine.

CentOS Linux release 7.4.1708 (Core)
Docker version 18.04.0-ce

It is strange the you having this issue. Does anything appers on your browser console? Nothing comes to my mind after everything works fine on me.

**Comment by salihciftci** [comment]
Thanks @vbrinza 

I will be waiting your feedback.
