### ISSUE TITLE
Basic management feature

### ISSUE THREAD

**Issue by salihciftci** [salihciftci/liman#8]
**Detailed Description**
Thinking about adding basic management features like starting/stopping containers, pulling/updating images etc.

**Comment by lukaspj** [comment]
The primary reason I'm using Liman over Portainer, is the fact that it's a monitoring tool and I can give people access to the service without giving them a carte blanche to everything for a container.
If this feature should go in, I would personally prefer if it went in after or hand-in-hand with #9.

**Comment by salihciftci** [comment]
Never used Portainer. 

Description says `.. for monitoring docker.`. Liman is a monitoring tool and it will stay like that. But I was thinking about basic management feature maybe not too bad. But still I'm not sure about that.

This feature won't implement to Liman without #9.
