### ISSUE TITLE
User management feature

### ISSUE THREAD

**Issue by salihciftci** [salihciftci/liman#9]
**Detailed Description**
Adding user management feature to Liman with user permissions.

Example:

User1 can watch stats but User2 can't.
User3 can only monitor but User4 can manage docker.

**Comment by lukaspj** [comment]
A thing worth taking into consideration:
It would be nice if this was decoupled in a way that made it easy to swap different authentication methods, e.g. AD or GitHub-based authentication.

**Comment by salihciftci** [comment]
This will make things easier. You can be sure that I shall work on it.

**Comment by salihciftci** [comment]
57a8bf817b819db1eaf55ff73a15c0f15497f29e
